name: Publish to Article

on:
  workflow_dispatch:
    inputs:
      PUBLICATION_TITLE:
        description: 'Title to publish to html'
        required: true
        default: ''
      INDUSTRY_KEYWORD:
        description: 'The main keyword from research'
        required: true
        default: ''
      PUBLICATION_TEXT:
        description: 'Text to publish to html'
        required: true
        default: 'Your article content here...'
      PUBLICATION_TAGS:
        description: 'Tags for article'
        required: true
        default: ''
      AUTHOR_LINK:
        description: 'Author link'
        required: true
        default: ''
      AUTHOR_NAME:
        description: 'Author name'
        required: true
        default: ''
      ABOUT_AUTHOR:
        description: 'About author'
        required: true
        default: ''
      CallToActionTitle:
        description: 'Call to action title'
        required: false
        default: ''
      CallToActionLink:
        description: 'Call to action link'
        required: false
        default: '#'
      CallToActionButton:
        description: 'Call to action button'
        required: false
        default: 'Start'

jobs:
  create_eeat_article:
    name: create_eeat_article
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Prepare git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git config pull.rebase false
      - name: Install Dependencies
        run: |
            pip install requests markdown

      - name: Create Post
        env:
          PUBLICATION_TITLE: ${{ github.event.inputs.PUBLICATION_TITLE }}
          PUBLICATION_TEXT: ${{ github.event.inputs.PUBLICATION_TEXT }}
          PUBLICATION_TAGS: ${{ github.event.inputs.PUBLICATION_TAGS }}
          AUTHOR_LINK: ${{ secrets.AUTHOR_LINK }}
          AUTHOR_NAME: ${{ secrets.AUTHOR_NAME }}
          ABOUT_AUTHOR: ${{ secrets.ABOUT_AUTHOR }}
          INDUSTRY_KEYWORD: ${{ secrets.INDUSTRY_KEYWORD }}
        run: |
          python 9visual_html.py
          git add -A
          git diff --cached --exit-code || git commit -m "($GITHUB_WORKFLOW)"
          git pull
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git || true