name: Publish to Medium

on:
  workflow_dispatch:
    inputs:
      MEDIUM_TITLE:
        description: 'Title to publish to Medium.com'
        required: true
        default: ''
      MEDIUM_TEXT:
        description: 'Text to publish to Medium.com'
        required: true
        default: 'Your article content here...'
      MEDIUM_TAGS:
        description: 'Tags for Medium.com'
        required: true
        default: ''

jobs:
  post-to-medium:
    name: Post to Medium
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Create Medium Post
        env:
          MEDIUM_INTEGRATION_TOKEN: ${{ secrets.MEDIUM_INTEGRATION_TOKEN }}
          MEDIUM_TITLE: ${{ github.event.inputs.MEDIUM_TITLE }}
          MEDIUM_TEXT: ${{ github.event.inputs.MEDIUM_TEXT }}
          MEDIUM_TAGS: ${{ github.event.inputs.MEDIUM_TAGS }}
        run: python publish_to_medium.py

